### ISSUE TITLE
Problem with nested content overlay when adding content

### ISSUE THREAD

**Issue by thomassen88** [skttl/umbraco-doc-type-grid-editor#158]
Hi, there is a problem with the overlay on nested content when you copy a content or adding a new content where you can choose between multiple content types.
The overlay works if you press the right side of the button, but not if you press in the middle or to the left. It also works if you downsize your browser-window.

I guess the problem has something to do with the absolute-position of the NC-overlay and 
 overflow:hidden somewhere in the DTGE-window.

This is not a problem for me, because i know about this, but my client is whining about it :p 

See problem in action in this screencast: https://recordit.co/0OtfM4RUjt

**Comment by skttl** [comment]
Thanks for reporting this. I think I remember seeing this was fixed in Umbraco earlier. What version are you on?

**Comment by hallojoe** [comment]
Hi, I am facing the same problem: Umbraco version 8.1.5.

**Comment by thomassen88** [comment]
Hi, i had version 8.1.3. i upgraded to 8.1.5 today, but i'm still facing the same problem.

**Comment by skttl** [comment]
Hi @thomassen88 and @hallojoe 

This seems to have been fixed in Umbraco 8.2

![2019-10-20_16-25-57](https://user-images.githubusercontent.com/3726467/67160976-62b0c600-f356-11e9-9709-833045dfd53e.gif)

**Comment by timeverts** [comment]
@skttl, Are you sure this has been resolved? I am running Umbraco 8.3 and still experiencing this exact issue:

![Nested_Content_Overlay_Bug](https://user-images.githubusercontent.com/15150632/70420075-cecfc080-1aa1-11ea-8d6f-c9f1f69a7188.gif)

**Comment by skttl** [comment]
At least in 8.2, if the error got back in 8.3, it is a bug in Umbraco, and should be posted there...

**Comment by timeverts** [comment]
> At least in 8.2, if the error got back in 8.3, it is a bug in Umbraco, and should be posted there...

There is an [open ticket #6032](https://github.com/umbraco/Umbraco-CMS/issues/6032) which sounds similar to the problem we are encountering here. But they've left it up to the community to resolve so not sure on a fix ETA! :(
