### ISSUE TITLE
Creating content templates automatically as DTGE Temp -{GUID}

### ISSUE THREAD

**Issue by MjDhaneshKumar** [skttl/umbraco-doc-type-grid-editor#256]
Hi,
On a client project where we are experiencing an issue that is very difficult to replicate. In Umbraco Backoffice => Settings => Content Templates, there are multiple Content Templates with names `dtge Temp: {GUID}`. and we can't replicate how these are created, but it is listed as "blueprints" in the doctype grid editor. We are now deleting these temp files manually from the content template.

Version using _**1.2.7**_

![Capture](https://user-images.githubusercontent.com/58820887/128362468-597a187b-b0ca-4f72-9574-a8f3053aa7b9.PNG)

**Comment by skttl** [comment]
Had this before, thought it was fixed. (#236)

Can you see if there are any console errors, when you save a DTGE editing dialog?

Which Umbraco version are you on?

**Comment by MjDhaneshKumar** [comment]
Hey,

Yes, but I am using the latest version(**_1.2.7_**), but the issue still exists.
Actually, this is very hard to replicate but I think this happens when we try to save a grid module that has a mandatory field, if I skip that field and try to save then it will show a validation error, but from the network payload I can see that, an API is calling `/umbraco/backoffice/UmbracoApi/Content/PostSaveBlueprint` and returns a 400(Bad Request) with the response below


`{"id":**3369**,"udi":"umb://document-blueprint/a23ec24968eb48d989d9d83d29142a7b","icon":"icon-code color-orange","trashed":false,"key":"a23ec249-68eb-48d9-89d9-d83d29142a7b","parentId":-1,"path":"-1,1112,3369","variants":[{"name":"Dtge Temp: e108ddc8-c548-4d85-a007-d77020b795ea","displayName":null,"tabs":[{"id":75,"active":true,"label":"Rich Text Block","alias":"#Rich Text Block Grid Tab","open":true,"properties":[{"label":"Body","description":"This text will show as Body Text of this page","view":"rte","config":{"editor":{"toolbar":["ace","removeformat","styleselect","bold","italic","underline","strikethrough","alignleft","aligncenter","alignright","alignjustify","bullist","numlist","outdent","indent","link","unlink","anchor","umbmediapicker","table","hr","subscript","superscript","charmap","rtl","ltr"],"stylesheets":["/css/rte.css"],"maxImageSize":500,"mode":"classic","dimensions":{"height":500}},"hideLabel":false,"ignoreUserStartNodes":false,"mediaParentId":null},"hideLabel":false,"labelOnTop":true,"validation":{"mandatory":true,"mandatoryMessage":"","pattern":"","patternMessage":""},"readonly":false,"id":0,"dataTypeKey":"e820ffca-7bee-4045-84e7-8f6e9621beca","value":"","alias":"body","editor":"Umbraco.TinyMCE","isSensitive":false,"culture":null,"segment":null}]}],"language":null,"segment":null,"state":"Draft","updateDate":"2021-08-06 05:41:32","createDate":"2021-08-06 05:41:32","publishDate":null,"releaseDate":null,"expireDate":null,"notifications":[]}],"owner":{"id":-1,"name":"Dhanesh"},"updater":{"id":-1,"name":"Dhanesh"},"contentTypeName":"Rich Text Block","isContainer":false,"isElement":true,"isChildOfListView":false,"treeNodeUrl":"/umbraco/backoffice/UmbracoTrees/ContentTree/GetTreeNode/a23ec24968eb48d989d9d83d29142a7b","contentTypeId":1112,"contentTypeKey":"90f18d4e-41b5-4bc1-be26-80f9bdf1e253","contentTypeAlias":"richTextBlock","sortOrder":1,"updateDate":"2021-08-06 05:41:32","template":null,"templateId":0,"allowedTemplates":{},"documentType":{"alias":"richTextBlock","updateDate":"2021-04-09 11:14:33","createDate":"2021-04-09 11:14:33","description":null,"thumbnail":"folder.png","iconIsClass":true,"iconFilePath":"","thumbnailIsClass":false,"thumbnailFilePath":"/umbraco/images/thumbnails/folder.png","blueprints":{},"isContainer":false,"isElement":true,"name":"Rich Text Block","id":1112,"udi":"umb://member-type/90f18d4e41b54bc1be2680f9bdf1e253","icon":"icon-code color-orange","trashed":false,"key":"90f18d4e-41b5-4bc1-be26-80f9bdf1e253","parentId":1092,"path":"-1,1092,1112","metaData":{}},"urls":[],"allowPreview":false,"allowedActions":["A"],"isBlueprint":true,"apps":[{"name":"Content","alias":"umbContent","weight":-100,"icon":"icon-document","view":"views/content/apps/content/content.html","viewModel":null,"active":false,"badge":null},{"name":"Info","alias":"umbInfo","weight":100,"icon":"icon-info","view":"views/content/apps/info/info.html","viewModel":null,"active":false,"badge":null}],"notifications":[],"ModelState":{"_Properties.body.invariant.null.value":["Value cannot be empty"]},"metaData":null}`


And after this call `PostSaveBluePrint` another Api call for deleting the created blueprint  `/umbraco/backoffice/UmbracoApi/Content/DeleteBlueprint?id=**3369**` and return 200

Maybe if the second call `DeleteBlueprint` fails then the blueprint will not delete and it remains as it is(this may be the issue)? but I can't say if this causes the issue or can't replicate how this is actually creating :(

UmbracoVersion : `**8.12.0**`
PackageVersion:    `**1.2.7**`

**Comment by MjDhaneshKumar** [comment]
Hey, @skttl  

FYI: we just updated the Umbraco to the latest version(8.15.1) and now in the QA environment there are no issues with blueprints, but anyway we keep an eye on it.
Please let me know,if any update on this :)
